apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
        labels:
          component: server
    spec:  # spec of each container that is to be created
      containers:
        - name: server
          image: ericwatts/multi-docker-deploy-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:                            # Gets value from command we ran: kubectl create secret generic pgpassword --from-literal PGPASSWORD=12345asdf
                secretKeyRef:
                  name: pgpassword            # name of secret as specified in command
                  key: PGPASSWORD                     # name of key as specified in command
